
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hw3 is a Catch v2.4.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Setting and Tracking Memory Used
-------------------------------------------------------------------------------
test.cpp:21
...............................................................................

test.cpp:35: FAILED:
  REQUIRE( cache->space_used() == 3 )
with expansion:
  2 == 3

-------------------------------------------------------------------------------
Getting Size
-------------------------------------------------------------------------------
test.cpp:88
...............................................................................

test.cpp:95: FAILED:
  REQUIRE( size == 1 )
with expansion:
  0 == 1

-------------------------------------------------------------------------------
Deleting
-------------------------------------------------------------------------------
test.cpp:103
...............................................................................

test.cpp:112: FAILED:
  REQUIRE( cache->get("a", size) == __null )
due to unexpected exception with message:
  key not contained in cache >:(

===============================================================================
test cases: 10 |  7 passed | 3 failed
assertions: 14 | 11 passed | 3 failed


RUN FINISHED; exit value 3; real time: 10ms; user: 0ms; system: 0ms
